name: "Continuous Integration"

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 1 * * *"

jobs:
  ci:
    uses: cjw296/python-workflow/.github/workflows/uv-ci.yml@v1
    with:
      package: paradigms
      python-versions: '[ "3.12", "3.13" ]'
