name: "Continuous Integration"

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 1 * * *"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'failure' && exit 1
